### ISSUE TITLE
React material + material icons

### ISSUE THREAD

**Issue by Mikkel94** [IT2810/it2810-webutvikling-h18-prosjekt-3-39#2]
Tittel sier seg selv.

https://material-ui.com/

**Comment by Mikkel94** [comment]
Det finnes kanskje en egen material bibliotek til react native???

**Comment by Oisov** [comment]
Ikke lengre relevant da paper krasjer med jest testene.

**Comment by fstorehaug** [comment]
Vi bruker paper noen steder.
