### ISSUE TITLE
Avtalebord/Kalender

### ISSUE THREAD

**Issue by Mikkel94** [IT2810/it2810-webutvikling-h18-prosjekt-3-39#4]
- [ ] UI
- [ ] Lage en ny avtale
- [ ] Legge til tidspunkt i avtale
- [ ] Mulighet for å koble en/flere kontakter til en avtale
- [ ] Mulighet for å få påminnelse om en avtale

**Comment by fstorehaug** [comment]
Vi rakk ikke implementere denne funksjonaliteten før deadline
