### ISSUE TITLE
Motivasjon/Livsmål

### ISSUE THREAD

**Issue by Mikkel94** [IT2810/it2810-webutvikling-h18-prosjekt-3-39#5]
- [ ] Registrering av mål
- [ ] Oppdatering av mål
- [ ] Sletting av mål (fordi de ikke lenger er mål)
- [ ] Sletting av mål (fordi du har nådd målet)
- [ ] Notifikasjoner om mål(ene)

Tenker at mål er noe du ønsker å gjøre x ganger i uka, f.eks. trene, og så kan appen minne deg på om det, og du kan krysse av for dager du har f.eks. trent inne på det målet.

**Comment by fstorehaug** [comment]
Vi rakk ikke å implementere denne funksjonaliteten før deadline
